### ISSUE TITLE
Combined media queries don't output correctly

### ISSUE THREAD

**Issue by allejo** [aaronjensen/sass-media_query_combiner#13]
This plug-in doesn't work when outputting the compiled and combined CSS to a file. For example, these two commands do not result in the same CSS.

**Doesn't work**

    $ sass web/assets/css/styles.scss web/assets/css/styles.css --style=expanded --sourcemap=auto --require=sass-media_query_combiner

**This works**

    $ sass web/assets/css/styles.scss --style=expanded --sourcemap=auto --require=sass-media_query_combiner > web/assets/css/styles.css

The latter of the two commands isn't an option since I'm using Grunt and can't modify the syntax of the command being executed. Is this a plug-in bug or an issue with Sass?

I'm using the Sass 3.4.12 but seems this issue has been around [since July 2014](https://github.com/gruntjs/grunt-contrib-sass/issues/67).

**Comment by aaronjensen** [comment]
@allejo thanks for the report. Fixed and 0.0.7 published. Let me know if it works out for you.

**Comment by allejo** [comment]
:+1: works like a charm! thanks!
