### ISSUE TITLE
Replace sass dependency by sassc

### ISSUE THREAD

**Issue by Fudoshiki** [aaronjensen/sass-media_query_combiner#14]
https://github.com/sass/ruby-sass
## Ruby Sass is Deprecated!

Ruby Sass is in a sunset period where only critical bugs and CSS compatibility
issues will be fixed. It will be completely unmaintained as of 26 March 2019.
See [the Sass website](https://sass-lang.com/ruby-sass) for details, and consider switching to the [`sassc`
gem](https://github.com/sass/sassc-ruby)

Related
https://github.com/rails/rails/issues/32896

**Comment by bemky** [comment]
I forked and made a `sassc` version here: https://github.com/bemky/sassc-media_query_combiner
